// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: post/api/proto/comment/comment.proto

package go_micro_api_post_comment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/hb-go/micro/post/srv/proto/comment"
	proto1 "github.com/micro/go-micro/api/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Comment service

type CommentService interface {
	Comments(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error)
}

type commentService struct {
	c    client.Client
	name string
}

func NewCommentService(name string, c client.Client) CommentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.api.post.comment"
	}
	return &commentService{
		c:    c,
		name: name,
	}
}

func (c *commentService) Comments(ctx context.Context, in *proto1.Request, opts ...client.CallOption) (*proto1.Response, error) {
	req := c.c.NewRequest(c.name, "Comment.Comments", in)
	out := new(proto1.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Comment service

type CommentHandler interface {
	Comments(context.Context, *proto1.Request, *proto1.Response) error
}

func RegisterCommentHandler(s server.Server, hdlr CommentHandler, opts ...server.HandlerOption) error {
	type comment interface {
		Comments(ctx context.Context, in *proto1.Request, out *proto1.Response) error
	}
	type Comment struct {
		comment
	}
	h := &commentHandler{hdlr}
	return s.Handle(s.NewHandler(&Comment{h}, opts...))
}

type commentHandler struct {
	CommentHandler
}

func (h *commentHandler) Comments(ctx context.Context, in *proto1.Request, out *proto1.Response) error {
	return h.CommentHandler.Comments(ctx, in, out)
}
