// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/api/proto/comment/comment.proto

/*
Package go_micro_api_post_comment is a generated protocol buffer package.

It is generated from these files:
	post/api/proto/comment/comment.proto

It has these top-level messages:
	Rsp
*/
package go_micro_api_post_comment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_api "github.com/micro/go-api/proto"
import go_micro_srv_post_comment "github.com/hb-go/micro/post/srv/proto/comment"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Rsp struct {
	Comments []*go_micro_srv_post_comment.CommentDto `protobuf:"bytes,1,rep,name=comments" json:"comments,omitempty"`
}

func (m *Rsp) Reset()                    { *m = Rsp{} }
func (m *Rsp) String() string            { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()               {}
func (*Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Rsp) GetComments() []*go_micro_srv_post_comment.CommentDto {
	if m != nil {
		return m.Comments
	}
	return nil
}

func init() {
	proto.RegisterType((*Rsp)(nil), "go.micro.api.post.comment.Rsp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Comment service

type CommentClient interface {
	Comments(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error)
}

type commentClient struct {
	c           client.Client
	serviceName string
}

func NewCommentClient(serviceName string, c client.Client) CommentClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.api.post.comment"
	}
	return &commentClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *commentClient) Comments(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error) {
	req := c.c.NewRequest(c.serviceName, "Comment.Comments", in)
	out := new(go_micro_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Comment service

type CommentHandler interface {
	Comments(context.Context, *go_micro_api.Request, *go_micro_api.Response) error
}

func RegisterCommentHandler(s server.Server, hdlr CommentHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Comment{hdlr}, opts...))
}

type Comment struct {
	CommentHandler
}

func (h *Comment) Comments(ctx context.Context, in *go_micro_api.Request, out *go_micro_api.Response) error {
	return h.CommentHandler.Comments(ctx, in, out)
}

func init() { proto.RegisterFile("post/api/proto/comment/comment.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x29, 0xc8, 0x2f, 0x2e,
	0xd1, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0x4d,
	0xcd, 0x2b, 0x81, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0xc9, 0xf4, 0x7c, 0xbd, 0xdc, 0xcc, 0xe4, 0xa2,
	0x7c, 0xbd, 0xc4, 0x82, 0x4c, 0x3d, 0x90, 0x16, 0x3d, 0xa8, 0x02, 0x29, 0xf5, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0x10, 0x5f, 0x1f, 0xac, 0x44, 0x3f, 0x3d, 0x5f, 0x17, 0x61, 0x1e, 0x58, 0x3d,
	0x88, 0x25, 0x65, 0x8d, 0xa4, 0x30, 0x23, 0x49, 0x37, 0x3d, 0x1f, 0xaa, 0x1c, 0xec, 0x80, 0xe2,
	0xa2, 0x32, 0x7c, 0x0e, 0x50, 0xf2, 0xe0, 0x62, 0x0e, 0x2a, 0x2e, 0x10, 0x72, 0xe4, 0xe2, 0x80,
	0x8a, 0x17, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0xa9, 0xea, 0xc1, 0x9d, 0x56, 0x5c, 0x54,
	0x86, 0xe2, 0x34, 0x3d, 0x67, 0x08, 0xed, 0x52, 0x92, 0x1f, 0x04, 0xd7, 0x66, 0xe4, 0xc6, 0xc5,
	0x0e, 0x15, 0x17, 0xb2, 0xe6, 0xe2, 0x80, 0x32, 0x8b, 0x85, 0x44, 0xf5, 0x50, 0xbc, 0x18, 0x94,
	0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x25, 0x86, 0x2e, 0x5c, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa,
	0xc4, 0x90, 0xc4, 0x06, 0x76, 0x98, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x1f, 0x89, 0x61,
	0x41, 0x01, 0x00, 0x00,
}
