// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: post/api/proto/comment/comment.proto

/*
Package go_micro_api_post_comment is a generated protocol buffer package.

It is generated from these files:
	post/api/proto/comment/comment.proto

It has these top-level messages:
	Rsp
*/
package go_micro_api_post_comment

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_api "github.com/micro/go-api/proto"
import _ "github.com/hb-go/micro/post/srv/proto/comment"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = go_api.Response{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Comment service

type CommentService interface {
	Comments(ctx context.Context, in *go_api.Request, opts ...client.CallOption) (*go_api.Response, error)
}

type commentService struct {
	c    client.Client
	name string
}

func NewCommentService(name string, c client.Client) CommentService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.api.post.comment"
	}
	return &commentService{
		c:    c,
		name: name,
	}
}

func (c *commentService) Comments(ctx context.Context, in *go_api.Request, opts ...client.CallOption) (*go_api.Response, error) {
	req := c.c.NewRequest(c.name, "Comment.Comments", in)
	out := new(go_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Comment service

type CommentHandler interface {
	Comments(context.Context, *go_api.Request, *go_api.Response) error
}

func RegisterCommentHandler(s server.Server, hdlr CommentHandler, opts ...server.HandlerOption) {
	type comment interface {
		Comments(ctx context.Context, in *go_api.Request, out *go_api.Response) error
	}
	type Comment struct {
		comment
	}
	h := &commentHandler{hdlr}
	s.Handle(s.NewHandler(&Comment{h}, opts...))
}

type commentHandler struct {
	CommentHandler
}

func (h *commentHandler) Comments(ctx context.Context, in *go_api.Request, out *go_api.Response) error {
	return h.CommentHandler.Comments(ctx, in, out)
}
