// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/api/proto/example/example.proto

/*
Package go_micro_api_account is a generated protocol buffer package.

It is generated from these files:
	account/api/proto/example/example.proto

It has these top-level messages:
*/
package go_micro_api_account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_micro_api "github.com/micro/go-api/proto"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Example service

type ExampleClient interface {
	Call(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error)
}

type exampleClient struct {
	c           client.Client
	serviceName string
}

func NewExampleClient(serviceName string, c client.Client) ExampleClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.api.account"
	}
	return &exampleClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *exampleClient) Call(ctx context.Context, in *go_micro_api.Request, opts ...client.CallOption) (*go_micro_api.Response, error) {
	req := c.c.NewRequest(c.serviceName, "Example.Call", in)
	out := new(go_micro_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Example service

type ExampleHandler interface {
	Call(context.Context, *go_micro_api.Request, *go_micro_api.Response) error
}

func RegisterExampleHandler(s server.Server, hdlr ExampleHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Example{hdlr}, opts...))
}

type Example struct {
	ExampleHandler
}

func (h *Example) Call(ctx context.Context, in *go_micro_api.Request, out *go_micro_api.Response) error {
	return h.ExampleHandler.Call(ctx, in, out)
}

func init() { proto.RegisterFile("account/api/proto/example/example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4f, 0xad,
	0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x85, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0x91, 0xf4, 0x7c, 0xbd, 0xdc,
	0xcc, 0xe4, 0xa2, 0x7c, 0xbd, 0xc4, 0x82, 0x4c, 0x3d, 0xa8, 0x2e, 0x29, 0xf5, 0xf4, 0xcc, 0x92,
	0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0xb0, 0xac, 0x7e, 0x7a, 0xbe, 0x2e, 0xc2, 0x28,
	0x90, 0x52, 0x30, 0xcb, 0xc8, 0x89, 0x8b, 0xdd, 0x15, 0x62, 0x9e, 0x90, 0x39, 0x17, 0x8b, 0x73,
	0x62, 0x4e, 0x8e, 0x90, 0xa8, 0x1e, 0x8a, 0x91, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x52,
	0x62, 0xe8, 0xc2, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0xa3, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0xfb, 0x04, 0x22, 0xb4, 0x00, 0x00, 0x00,
}
