// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth/srv/proto/token/token.proto

/*
Package go_micro_srv_auth_token is a generated protocol buffer package.

It is generated from these files:
	auth/srv/proto/token/token.proto

It has these top-level messages:
	ReqKey
	ReqToken
	Rsp
*/
package go_micro_srv_auth_token

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Token service

type TokenService interface {
	Generate(ctx context.Context, in *ReqKey, opts ...client.CallOption) (*Rsp, error)
	Verify(ctx context.Context, in *ReqToken, opts ...client.CallOption) (*Rsp, error)
}

type tokenService struct {
	c    client.Client
	name string
}

func NewTokenService(name string, c client.Client) TokenService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.auth.token"
	}
	return &tokenService{
		c:    c,
		name: name,
	}
}

func (c *tokenService) Generate(ctx context.Context, in *ReqKey, opts ...client.CallOption) (*Rsp, error) {
	req := c.c.NewRequest(c.name, "Token.Generate", in)
	out := new(Rsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenService) Verify(ctx context.Context, in *ReqToken, opts ...client.CallOption) (*Rsp, error) {
	req := c.c.NewRequest(c.name, "Token.Verify", in)
	out := new(Rsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Token service

type TokenHandler interface {
	Generate(context.Context, *ReqKey, *Rsp) error
	Verify(context.Context, *ReqToken, *Rsp) error
}

func RegisterTokenHandler(s server.Server, hdlr TokenHandler, opts ...server.HandlerOption) {
	type token interface {
		Generate(ctx context.Context, in *ReqKey, out *Rsp) error
		Verify(ctx context.Context, in *ReqToken, out *Rsp) error
	}
	type Token struct {
		token
	}
	h := &tokenHandler{hdlr}
	s.Handle(s.NewHandler(&Token{h}, opts...))
}

type tokenHandler struct {
	TokenHandler
}

func (h *tokenHandler) Generate(ctx context.Context, in *ReqKey, out *Rsp) error {
	return h.TokenHandler.Generate(ctx, in, out)
}

func (h *tokenHandler) Verify(ctx context.Context, in *ReqToken, out *Rsp) error {
	return h.TokenHandler.Verify(ctx, in, out)
}
