// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/srv/proto/post/post.proto

/*
Package go_micro_srv_post is a generated protocol buffer package.

It is generated from these files:
	post/srv/proto/post/post.proto

It has these top-level messages:
	ReqPost
	RspPost
*/
package go_micro_srv_post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReqPost struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReqPost) Reset()                    { *m = ReqPost{} }
func (m *ReqPost) String() string            { return proto.CompactTextString(m) }
func (*ReqPost) ProtoMessage()               {}
func (*ReqPost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReqPost) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RspPost struct {
	Id      int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *RspPost) Reset()                    { *m = RspPost{} }
func (m *RspPost) String() string            { return proto.CompactTextString(m) }
func (*RspPost) ProtoMessage()               {}
func (*RspPost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RspPost) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RspPost) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RspPost) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqPost)(nil), "go.micro.srv.post.ReqPost")
	proto.RegisterType((*RspPost)(nil), "go.micro.srv.post.RspPost")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Post service

type PostClient interface {
	GetPost(ctx context.Context, in *ReqPost, opts ...client.CallOption) (*RspPost, error)
}

type postClient struct {
	c           client.Client
	serviceName string
}

func NewPostClient(serviceName string, c client.Client) PostClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.post"
	}
	return &postClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *postClient) GetPost(ctx context.Context, in *ReqPost, opts ...client.CallOption) (*RspPost, error) {
	req := c.c.NewRequest(c.serviceName, "Post.GetPost", in)
	out := new(RspPost)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Post service

type PostHandler interface {
	GetPost(context.Context, *ReqPost, *RspPost) error
}

func RegisterPostHandler(s server.Server, hdlr PostHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Post{hdlr}, opts...))
}

type Post struct {
	PostHandler
}

func (h *Post) GetPost(ctx context.Context, in *ReqPost, out *RspPost) error {
	return h.PostHandler.GetPost(ctx, in, out)
}

func init() { proto.RegisterFile("post/srv/proto/post/post.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xc8, 0x2f, 0x2e,
	0xd1, 0x2f, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x07, 0x73, 0x41, 0x84, 0x1e,
	0x98, 0x2f, 0x24, 0x98, 0x9e, 0xaf, 0x97, 0x9b, 0x99, 0x5c, 0x94, 0xaf, 0x57, 0x5c, 0x54, 0xa6,
	0x07, 0x92, 0x50, 0x92, 0xe4, 0x62, 0x0f, 0x4a, 0x2d, 0x0c, 0xc8, 0x2f, 0x2e, 0x11, 0xe2, 0xe3,
	0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62, 0xca, 0x4c, 0x51, 0xf2, 0xe4,
	0x62, 0x0f, 0x2a, 0x2e, 0xc0, 0x26, 0x25, 0x24, 0xc2, 0xc5, 0x5a, 0x92, 0x59, 0x92, 0x93, 0x2a,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x49, 0x70, 0xb1, 0x27, 0xe7, 0xe7, 0x95,
	0xa4, 0xe6, 0x95, 0x48, 0x30, 0x83, 0xc5, 0x61, 0x5c, 0x23, 0x6f, 0x2e, 0x16, 0xb0, 0x39, 0xce,
	0x5c, 0xec, 0xee, 0xa9, 0x25, 0x60, 0xa6, 0x94, 0x1e, 0x86, 0x63, 0xf4, 0xa0, 0x2e, 0x91, 0xc2,
	0x2a, 0x07, 0x71, 0x8a, 0x12, 0x43, 0x12, 0x1b, 0xd8, 0x33, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xef, 0x6c, 0xe5, 0x8b, 0xee, 0x00, 0x00, 0x00,
}
