// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post/srv/proto/post/post.proto

/*
Package go_micro_srv_post is a generated protocol buffer package.

It is generated from these files:
	post/srv/proto/post/post.proto

It has these top-level messages:
	Message
	Request
	Response
	StreamingRequest
	StreamingResponse
	Ping
	Pong
*/
package go_micro_srv_post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Say string `protobuf:"bytes,1,opt,name=say" json:"say,omitempty"`
	P   string `protobuf:"bytes,2,opt,name=p" json:"p,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetSay() string {
	if m != nil {
		return m.Say
	}
	return ""
}

func (m *Message) GetP() string {
	if m != nil {
		return m.P
	}
	return ""
}

type Request struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamingRequest struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingRequest) Reset()                    { *m = StreamingRequest{} }
func (m *StreamingRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamingRequest) ProtoMessage()               {}
func (*StreamingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StreamingRequest) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type StreamingResponse struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *StreamingResponse) Reset()                    { *m = StreamingResponse{} }
func (m *StreamingResponse) String() string            { return proto.CompactTextString(m) }
func (*StreamingResponse) ProtoMessage()               {}
func (*StreamingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StreamingResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Ping struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Ping) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

type Pong struct {
	Stroke int64 `protobuf:"varint,1,opt,name=stroke" json:"stroke,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Pong) GetStroke() int64 {
	if m != nil {
		return m.Stroke
	}
	return 0
}

func init() {
	proto.RegisterType((*Message)(nil), "go.micro.srv.post.Message")
	proto.RegisterType((*Request)(nil), "go.micro.srv.post.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.post.Response")
	proto.RegisterType((*StreamingRequest)(nil), "go.micro.srv.post.StreamingRequest")
	proto.RegisterType((*StreamingResponse)(nil), "go.micro.srv.post.StreamingResponse")
	proto.RegisterType((*Ping)(nil), "go.micro.srv.post.Ping")
	proto.RegisterType((*Pong)(nil), "go.micro.srv.post.Pong")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Post service

type PostClient interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Post_StreamClient, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Post_PingPongClient, error)
}

type postClient struct {
	c           client.Client
	serviceName string
}

func NewPostClient(serviceName string, c client.Client) PostClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.post"
	}
	return &postClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *postClient) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "Post.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Post_StreamClient, error) {
	req := c.c.NewRequest(c.serviceName, "Post.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &postStreamClient{stream}, nil
}

type Post_StreamClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type postStreamClient struct {
	stream client.Streamer
}

func (x *postStreamClient) Close() error {
	return x.stream.Close()
}

func (x *postStreamClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postStreamClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postStreamClient) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *postClient) PingPong(ctx context.Context, opts ...client.CallOption) (Post_PingPongClient, error) {
	req := c.c.NewRequest(c.serviceName, "Post.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &postPingPongClient{stream}, nil
}

type Post_PingPongClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type postPingPongClient struct {
	stream client.Streamer
}

func (x *postPingPongClient) Close() error {
	return x.stream.Close()
}

func (x *postPingPongClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postPingPongClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postPingPongClient) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *postPingPongClient) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Post service

type PostHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Post_StreamStream) error
	PingPong(context.Context, Post_PingPongStream) error
}

func RegisterPostHandler(s server.Server, hdlr PostHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Post{hdlr}, opts...))
}

type Post struct {
	PostHandler
}

func (h *Post) Call(ctx context.Context, in *Request, out *Response) error {
	return h.PostHandler.Call(ctx, in, out)
}

func (h *Post) Stream(ctx context.Context, stream server.Streamer) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.PostHandler.Stream(ctx, m, &postStreamStream{stream})
}

type Post_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type postStreamStream struct {
	stream server.Streamer
}

func (x *postStreamStream) Close() error {
	return x.stream.Close()
}

func (x *postStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *Post) PingPong(ctx context.Context, stream server.Streamer) error {
	return h.PostHandler.PingPong(ctx, &postPingPongStream{stream})
}

type Post_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type postPingPongStream struct {
	stream server.Streamer
}

func (x *postPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *postPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *postPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *postPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *postPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func init() { proto.RegisterFile("post/srv/proto/post/post.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0xbb, 0x5f, 0xf3, 0xa5, 0x75, 0xf0, 0xd0, 0x0e, 0xa2, 0x25, 0x6a, 0x91, 0xd5, 0x43,
	0x7a, 0xd9, 0x14, 0xfd, 0x05, 0xea, 0x59, 0x90, 0x78, 0xf0, 0x1c, 0xcb, 0xb2, 0x04, 0x9b, 0xdd,
	0xb8, 0xb3, 0x2d, 0xf8, 0x87, 0xfd, 0x1d, 0xb2, 0x9b, 0x04, 0x44, 0x57, 0x2f, 0x61, 0x5e, 0x9e,
	0x27, 0x2f, 0x33, 0x09, 0x2c, 0x5b, 0x43, 0xae, 0x20, 0xbb, 0x2f, 0x5a, 0x6b, 0x9c, 0x29, 0x42,
	0xf4, 0x0f, 0x11, 0x32, 0xce, 0x95, 0x11, 0x4d, 0xbd, 0xb1, 0x46, 0x90, 0xdd, 0x0b, 0x0f, 0xf8,
	0x0a, 0x26, 0x0f, 0x92, 0xa8, 0x52, 0x12, 0x67, 0x30, 0xa6, 0xea, 0x7d, 0xc1, 0x2e, 0x58, 0x7e,
	0x50, 0xfa, 0x11, 0x0f, 0x81, 0xb5, 0x8b, 0x7f, 0x21, 0xb3, 0x96, 0x9f, 0xc3, 0xa4, 0x94, 0x6f,
	0x3b, 0x49, 0x0e, 0x11, 0x12, 0x5d, 0x35, 0xb2, 0x77, 0xc3, 0xcc, 0xcf, 0x60, 0x5a, 0x4a, 0x6a,
	0x8d, 0xa6, 0x50, 0xd5, 0x90, 0x1a, 0xaa, 0x1a, 0x52, 0x3c, 0x87, 0xd9, 0x93, 0xb3, 0xb2, 0x6a,
	0x6a, 0xad, 0x86, 0x96, 0x23, 0xf8, 0xbf, 0x31, 0x3b, 0xed, 0x82, 0x37, 0x2e, 0xbb, 0xc0, 0x57,
	0x30, 0xff, 0x62, 0xf6, 0x85, 0x71, 0x75, 0x09, 0xc9, 0x63, 0xad, 0x15, 0x1e, 0x43, 0x4a, 0xce,
	0x9a, 0x57, 0xd9, 0xe3, 0x3e, 0x05, 0x6e, 0x7e, 0xe7, 0xd7, 0x1f, 0xcc, 0x0b, 0xe4, 0xf0, 0x16,
	0x92, 0xfb, 0x6a, 0xbb, 0xc5, 0x4c, 0xfc, 0xf8, 0x42, 0xa2, 0xdf, 0x36, 0x3b, 0x8d, 0xb2, 0x6e,
	0x3f, 0x3e, 0xc2, 0x67, 0x48, 0xbb, 0xb5, 0xf1, 0x32, 0x22, 0x7e, 0xbf, 0x3d, 0xbb, 0xfa, 0x5b,
	0x1a, 0x6a, 0xd7, 0x0c, 0xef, 0x60, 0xea, 0x8f, 0x0c, 0x87, 0x9c, 0x44, 0xde, 0xf2, 0x30, 0x8b,
	0x02, 0xa3, 0x15, 0x1f, 0xe5, 0x6c, 0xcd, 0x5e, 0xd2, 0xf0, 0xff, 0x6f, 0x3e, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x71, 0x47, 0x94, 0xc6, 0x21, 0x02, 0x00, 0x00,
}
