// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: post/srv/proto/post/post.proto

/*
Package go_micro_srv_post is a generated protocol buffer package.

It is generated from these files:
	post/srv/proto/post/post.proto

It has these top-level messages:
	Req
	Rsp
*/
package go_micro_srv_post

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Post service

type PostService interface {
	GetPost(ctx context.Context, in *Req, opts ...client.CallOption) (*Rsp, error)
}

type postService struct {
	c    client.Client
	name string
}

func NewPostService(name string, c client.Client) PostService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.post"
	}
	return &postService{
		c:    c,
		name: name,
	}
}

func (c *postService) GetPost(ctx context.Context, in *Req, opts ...client.CallOption) (*Rsp, error) {
	req := c.c.NewRequest(c.name, "Post.GetPost", in)
	out := new(Rsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Post service

type PostHandler interface {
	GetPost(context.Context, *Req, *Rsp) error
}

func RegisterPostHandler(s server.Server, hdlr PostHandler, opts ...server.HandlerOption) {
	type post interface {
		GetPost(ctx context.Context, in *Req, out *Rsp) error
	}
	type Post struct {
		post
	}
	h := &postHandler{hdlr}
	s.Handle(s.NewHandler(&Post{h}, opts...))
}

type postHandler struct {
	PostHandler
}

func (h *postHandler) GetPost(ctx context.Context, in *Req, out *Rsp) error {
	return h.PostHandler.GetPost(ctx, in, out)
}
