// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth/srv/proto/user/user.proto

/*
Package go_micro_srv_auth_user is a generated protocol buffer package.

It is generated from these files:
	auth/srv/proto/user/user.proto

It has these top-level messages:
	ReqId
	ReqLogin
	Rsp
*/
package go_micro_srv_auth_user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	GetUser(ctx context.Context, in *ReqId, opts ...client.CallOption) (*Rsp, error)
	GetUserLogin(ctx context.Context, in *ReqLogin, opts ...client.CallOption) (*Rsp, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.auth.user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) GetUser(ctx context.Context, in *ReqId, opts ...client.CallOption) (*Rsp, error) {
	req := c.c.NewRequest(c.name, "User.GetUser", in)
	out := new(Rsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserLogin(ctx context.Context, in *ReqLogin, opts ...client.CallOption) (*Rsp, error) {
	req := c.c.NewRequest(c.name, "User.GetUserLogin", in)
	out := new(Rsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	GetUser(context.Context, *ReqId, *Rsp) error
	GetUserLogin(context.Context, *ReqLogin, *Rsp) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) {
	type user interface {
		GetUser(ctx context.Context, in *ReqId, out *Rsp) error
		GetUserLogin(ctx context.Context, in *ReqLogin, out *Rsp) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) GetUser(ctx context.Context, in *ReqId, out *Rsp) error {
	return h.UserHandler.GetUser(ctx, in, out)
}

func (h *userHandler) GetUserLogin(ctx context.Context, in *ReqLogin, out *Rsp) error {
	return h.UserHandler.GetUserLogin(ctx, in, out)
}
