// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/srv/proto/user/user.proto

package go_micro_srv_auth_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqId struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqId) Reset()         { *m = ReqId{} }
func (m *ReqId) String() string { return proto.CompactTextString(m) }
func (*ReqId) ProtoMessage()    {}
func (*ReqId) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc07bead22c97b6, []int{0}
}

func (m *ReqId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqId.Unmarshal(m, b)
}
func (m *ReqId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqId.Marshal(b, m, deterministic)
}
func (m *ReqId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqId.Merge(m, src)
}
func (m *ReqId) XXX_Size() int {
	return xxx_messageInfo_ReqId.Size(m)
}
func (m *ReqId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqId proto.InternalMessageInfo

func (m *ReqId) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReqLogin struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc07bead22c97b6, []int{1}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ReqLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type Rsp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rsp) Reset()         { *m = Rsp{} }
func (m *Rsp) String() string { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()    {}
func (*Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcc07bead22c97b6, []int{2}
}

func (m *Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsp.Unmarshal(m, b)
}
func (m *Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsp.Marshal(b, m, deterministic)
}
func (m *Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsp.Merge(m, src)
}
func (m *Rsp) XXX_Size() int {
	return xxx_messageInfo_Rsp.Size(m)
}
func (m *Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Rsp proto.InternalMessageInfo

func (m *Rsp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rsp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqId)(nil), "go.micro.srv.auth.user.ReqId")
	proto.RegisterType((*ReqLogin)(nil), "go.micro.srv.auth.user.ReqLogin")
	proto.RegisterType((*Rsp)(nil), "go.micro.srv.auth.user.Rsp")
}

func init() { proto.RegisterFile("auth/srv/proto/user/user.proto", fileDescriptor_fcc07bead22c97b6) }

var fileDescriptor_fcc07bead22c97b6 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2f, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x2f, 0x2d, 0x4e, 0x2d, 0x02,
	0x13, 0x7a, 0x60, 0xbe, 0x90, 0x58, 0x7a, 0xbe, 0x5e, 0x6e, 0x66, 0x72, 0x51, 0xbe, 0x5e, 0x71,
	0x51, 0x99, 0x1e, 0x48, 0xb1, 0x1e, 0x48, 0x56, 0x49, 0x9c, 0x8b, 0x35, 0x28, 0xb5, 0xd0, 0x33,
	0x45, 0x88, 0x8f, 0x8b, 0x29, 0x33, 0x45, 0x82, 0x51, 0x81, 0x51, 0x83, 0x39, 0x88, 0x29, 0x33,
	0x45, 0xc9, 0x82, 0x8b, 0x23, 0x28, 0xb5, 0xd0, 0x27, 0x3f, 0x3d, 0x33, 0x4f, 0x48, 0x8a, 0x8b,
	0x23, 0x2f, 0x33, 0x39, 0x3b, 0x2f, 0x31, 0x37, 0x15, 0xac, 0x82, 0x33, 0x08, 0xce, 0x17, 0x12,
	0xe0, 0x62, 0x2e, 0x28, 0x4f, 0x91, 0x60, 0x02, 0x0b, 0x83, 0x98, 0x4a, 0x86, 0x5c, 0xcc, 0x41,
	0xc5, 0x05, 0xe8, 0x06, 0xa2, 0x18, 0xc2, 0x84, 0x6a, 0x88, 0xd1, 0x02, 0x46, 0x2e, 0x96, 0xd0,
	0xe2, 0xd4, 0x22, 0x21, 0x77, 0x2e, 0x76, 0xf7, 0xd4, 0x12, 0x30, 0x53, 0x56, 0x0f, 0xbb, 0x93,
	0xf5, 0xc0, 0xee, 0x95, 0x92, 0xc6, 0x29, 0x5d, 0x5c, 0xa0, 0xc4, 0x20, 0xe4, 0xcf, 0xc5, 0x03,
	0x35, 0x08, 0xe2, 0x05, 0x05, 0x3c, 0xa6, 0x81, 0x55, 0x10, 0x30, 0x30, 0x89, 0x0d, 0x1c, 0x8e,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xa7, 0x1d, 0x02, 0x69, 0x01, 0x00, 0x00,
}
