// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/api/proto/account/account.proto

package go_micro_api_account

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/micro/go-micro/api/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqLogin struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_204f3613b9b14a22, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ReqLogin) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type ReqRegister struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	PwdRe                string   `protobuf:"bytes,3,opt,name=pwdRe,proto3" json:"pwdRe,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegister) Reset()         { *m = ReqRegister{} }
func (m *ReqRegister) String() string { return proto.CompactTextString(m) }
func (*ReqRegister) ProtoMessage()    {}
func (*ReqRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_204f3613b9b14a22, []int{1}
}

func (m *ReqRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegister.Unmarshal(m, b)
}
func (m *ReqRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegister.Marshal(b, m, deterministic)
}
func (m *ReqRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegister.Merge(m, src)
}
func (m *ReqRegister) XXX_Size() int {
	return xxx_messageInfo_ReqRegister.Size(m)
}
func (m *ReqRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegister.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegister proto.InternalMessageInfo

func (m *ReqRegister) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *ReqRegister) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *ReqRegister) GetPwdRe() string {
	if m != nil {
		return m.PwdRe
	}
	return ""
}

type Rsp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rsp) Reset()         { *m = Rsp{} }
func (m *Rsp) String() string { return proto.CompactTextString(m) }
func (*Rsp) ProtoMessage()    {}
func (*Rsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_204f3613b9b14a22, []int{2}
}

func (m *Rsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsp.Unmarshal(m, b)
}
func (m *Rsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsp.Marshal(b, m, deterministic)
}
func (m *Rsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsp.Merge(m, src)
}
func (m *Rsp) XXX_Size() int {
	return xxx_messageInfo_Rsp.Size(m)
}
func (m *Rsp) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsp.DiscardUnknown(m)
}

var xxx_messageInfo_Rsp proto.InternalMessageInfo

func (m *Rsp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Rsp) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Rsp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "go.micro.api.account.ReqLogin")
	proto.RegisterType((*ReqRegister)(nil), "go.micro.api.account.ReqRegister")
	proto.RegisterType((*Rsp)(nil), "go.micro.api.account.Rsp")
}

func init() {
	proto.RegisterFile("account/api/proto/account/account.proto", fileDescriptor_204f3613b9b14a22)
}

var fileDescriptor_204f3613b9b14a22 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x86, 0x69, 0xa2, 0x40, 0x39, 0x24, 0xa8, 0xac, 0x0c, 0x51, 0x26, 0x94, 0x05, 0x06, 0x6a,
	0x4b, 0xb0, 0xb0, 0x32, 0xb1, 0xb0, 0xe0, 0x7f, 0x90, 0x26, 0x27, 0xf7, 0x54, 0xc5, 0xe7, 0xc4,
	0x8e, 0xfa, 0xf7, 0x51, 0xed, 0x52, 0x3e, 0x26, 0x98, 0xec, 0xf7, 0x39, 0xdd, 0x23, 0xdd, 0x0b,
	0x77, 0x6d, 0xd7, 0xf1, 0x6c, 0x83, 0x6a, 0x1d, 0x29, 0x37, 0x71, 0x60, 0x75, 0x22, 0xe9, 0x95,
	0x91, 0x8a, 0xd2, 0xb0, 0x1c, 0xa8, 0x9b, 0x58, 0xb6, 0x8e, 0xe4, 0x71, 0x56, 0xaf, 0x0d, 0x85,
	0xed, 0xbc, 0x91, 0x1d, 0x0f, 0x2a, 0x4e, 0x95, 0xe1, 0x75, 0xfa, 0x7c, 0x13, 0x3a, 0x4a, 0x92,
	0xe6, 0x19, 0x96, 0x1a, 0xc7, 0x37, 0x36, 0x64, 0x45, 0x0d, 0x4b, 0x4b, 0xdd, 0xce, 0xb6, 0x03,
	0x56, 0x8b, 0xdb, 0xc5, 0xfd, 0xa5, 0x3e, 0x65, 0xb1, 0x82, 0xdc, 0xed, 0xfb, 0x2a, 0x8b, 0xf8,
	0xf0, 0x6d, 0xde, 0xe1, 0x4a, 0xe3, 0xa8, 0xd1, 0x90, 0x0f, 0x38, 0xfd, 0x6f, 0x59, 0x94, 0x50,
	0xb8, 0x7d, 0xaf, 0xb1, 0xca, 0x23, 0x4b, 0xa1, 0x79, 0x85, 0x5c, 0x7b, 0x27, 0xae, 0x21, 0xa3,
	0x3e, 0x4a, 0x72, 0x9d, 0x51, 0xff, 0x43, 0x9d, 0xfd, 0x52, 0x97, 0x50, 0x04, 0xde, 0xa1, 0xfd,
	0x14, 0xc5, 0xf0, 0xb8, 0x85, 0x8b, 0x97, 0xd4, 0x87, 0x78, 0x80, 0x22, 0x5d, 0x77, 0x23, 0x4d,
	0x6a, 0x4a, 0xe3, 0x38, 0xa3, 0x0f, 0xf5, 0xea, 0x0b, 0x78, 0xc7, 0xd6, 0x63, 0x73, 0x26, 0xd4,
	0xa1, 0x8e, 0xe3, 0x45, 0x7f, 0x59, 0xd8, 0x9c, 0xc7, 0x1a, 0x9f, 0x3e, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x8b, 0xc4, 0x53, 0x6a, 0xb6, 0x01, 0x00, 0x00,
}
